name: Build Geode Mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build git curl

      - name: Setup Geode CLI
        run: |
          URL=$(curl -s https://api.github.com/repos/geode-sdk/cli/releases/latest \
            | grep "browser_download_url" \
            | grep "linux" \
            | cut -d '"' -f 4)

          echo "Downloading: $URL"
          curl -L $URL -o geode.tar.gz

          tar -xzf geode.tar.gz

          sudo mv geode /usr/local/bin/geode

          geode --version

      - name: Configure build
        run: |
          mkdir -p build
          cd build
          cmake .. -G Ninja

      - name: Build mod
        run: |
          cd build
          ninja

      - name: Package mod
        run: |
          cd build
          geode package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RipBot-geode
          path: build/*.geode
